-- ============================================================
-- ECOAGRIS
-- Initial ECOWAS Agricultural & Livestock Data Schema
-- Migration: 001_ecowas_agriculture_livestock
-- ============================================================

create table if not exists public.countries (
    id bigint generated by default as identity primary key,
    name text not null unique,
    iso_code char(3) unique,
    region text not null default 'ECOWAS',
    is_ecowas boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.datasets (
    id bigint generated by default as identity primary key,
    name text not null unique,
    description text,
    sector text not null,
    data_type text not null default 'simulated',
    geographical_scope text not null default 'ECOWAS',
    start_year integer,
    end_year integer,
    source text,
    file_name text,
    version text default '1.0',
    status text not null default 'active',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint datasets_data_type_check
        check (data_type in ('observed', 'simulated', 'derived')),

    constraint datasets_status_check
        check (status in ('active', 'archived', 'draft')),

    constraint datasets_year_check
        check (
            start_year is null
            or end_year is null
            or start_year <= end_year
        )
);

create table if not exists public.agricultural_inputs (
    id bigint generated by default as identity primary key,
    country_id bigint not null
        references public.countries(id)
        on delete restrict,
    year integer not null,

    cereal_seeds_tons numeric(18,2),
    fertilizer_tons numeric(18,2),
    pesticide_liters numeric(18,2),
    improved_seed_use_pct numeric(8,2),
    fertilizer_kg_per_ha numeric(12,2),
    input_price_index_2006_base numeric(12,4),
    agro_dealer_count integer,
    input_subsidy_budget_usd numeric(20,2),
    distribution_timeliness_pct numeric(8,2),
    stockouts_days_per_year integer,
    input_import_value_usd numeric(20,2),
    local_production_inputs_tons numeric(18,2),
    mechanization_units_per_1000_farms numeric(12,2),
    credit_access_pct numeric(8,2),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint agricultural_inputs_year_check
        check (year between 1900 and 2100),

    constraint agricultural_inputs_country_year_unique
        unique (country_id, year)
);

create table if not exists public.livestock_data (
    id bigint generated by default as identity primary key,
    country_id bigint not null
        references public.countries(id)
        on delete restrict,
    year integer not null,

    cattle_head numeric(20,2),
    small_ruminants_head numeric(20,2),
    pigs_head numeric(20,2),
    poultry_head numeric(20,2),
    milk_production_tons numeric(20,2),
    meat_production_tons numeric(20,2),
    livestock_price_index_2006_base numeric(12,4),
    vaccination_coverage_pct numeric(8,2),
    fmd_incidents_count integer,
    grazing_area_ha numeric(20,2),
    transhumance_events integer,
    veterinary_facilities_count integer,
    feed_imports_tons numeric(20,2),
    local_feed_production_tons numeric(20,2),
    livestock_exports_tons numeric(20,2),
    offtake_rate_pct numeric(8,2),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint livestock_data_year_check
        check (year between 1900 and 2100),

    constraint livestock_data_country_year_unique
        unique (country_id, year)
);

create index if not exists idx_countries_name
    on public.countries(name);

create index if not exists idx_countries_ecowas
    on public.countries(is_ecowas);

create index if not exists idx_agricultural_inputs_country
    on public.agricultural_inputs(country_id);

create index if not exists idx_agricultural_inputs_year
    on public.agricultural_inputs(year);

create index if not exists idx_agricultural_inputs_country_year
    on public.agricultural_inputs(country_id, year);

create index if not exists idx_livestock_data_country
    on public.livestock_data(country_id);

create index if not exists idx_livestock_data_year
    on public.livestock_data(year);

create index if not exists idx_livestock_data_country_year
    on public.livestock_data(country_id, year);

create index if not exists idx_datasets_sector
    on public.datasets(sector);

create index if not exists idx_datasets_data_type
    on public.datasets(data_type);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_datasets_updated_at
    on public.datasets;

create trigger set_datasets_updated_at
before update on public.datasets
for each row
execute function public.set_updated_at();

drop trigger if exists set_agricultural_inputs_updated_at
    on public.agricultural_inputs;

create trigger set_agricultural_inputs_updated_at
before update on public.agricultural_inputs
for each row
execute function public.set_updated_at();

drop trigger if exists set_livestock_data_updated_at
    on public.livestock_data;

create trigger set_livestock_data_updated_at
before update on public.livestock_data
for each row
execute function public.set_updated_at();

insert into public.countries
    (name, iso_code, region, is_ecowas)
values
    ('Benin', 'BEN', 'ECOWAS', true),
    ('Burkina Faso', 'BFA', 'ECOWAS', true),
    ('Cabo Verde', 'CPV', 'ECOWAS', true),
    ('Côte d''Ivoire', 'CIV', 'ECOWAS', true),
    ('Gambia', 'GMB', 'ECOWAS', true),
    ('Ghana', 'GHA', 'ECOWAS', true),
    ('Guinea', 'GIN', 'ECOWAS', true),
    ('Guinea-Bissau', 'GNB', 'ECOWAS', true),
    ('Liberia', 'LBR', 'ECOWAS', true),
    ('Mali', 'MLI', 'ECOWAS', true),
    ('Niger', 'NER', 'ECOWAS', true),
    ('Nigeria', 'NGA', 'ECOWAS', true),
    ('Senegal', 'SEN', 'ECOWAS', true),
    ('Sierra Leone', 'SLE', 'ECOWAS', true),
    ('Togo', 'TGO', 'ECOWAS', true)
on conflict (name) do update
set
    iso_code = excluded.iso_code,
    region = excluded.region,
    is_ecowas = excluded.is_ecowas;

insert into public.datasets (
    name,
    description,
    sector,
    data_type,
    geographical_scope,
    start_year,
    end_year,
    source,
    file_name,
    version,
    status
)
values
(
    'APMD ECOWAS Input Simulation',
    'ECOWAS agricultural input indicators covering seeds, fertilizer, pesticides, input prices, subsidies, distribution, imports, local production, mechanization and credit access.',
    'Agricultural Inputs',
    'simulated',
    'ECOWAS',
    2006,
    2025,
    'APMD ECOWAS',
    'APMD_ECOWAS_Input_Simulated_2006_2025_1.xlsx',
    '1.0',
    'active'
),
(
    'APMD ECOWAS Livestock Data',
    'ECOWAS livestock indicators covering animal populations, production, prices, vaccination, disease incidents, grazing, transhumance, veterinary facilities, feed and livestock trade.',
    'Livestock',
    'simulated',
    'ECOWAS',
    2006,
    2025,
    'APMD ECOWAS',
    'APMD_ECOWAS_Livestock_2006_2025.xlsx',
    '1.0',
    'active'
)
on conflict (name) do update
set
    description = excluded.description,
    sector = excluded.sector,
    data_type = excluded.data_type,
    geographical_scope = excluded.geographical_scope,
    start_year = excluded.start_year,
    end_year = excluded.end_year,
    source = excluded.source,
    file_name = excluded.file_name,
    version = excluded.version,
    status = excluded.status,
    updated_at = now();

alter table public.countries enable row level security;
alter table public.datasets enable row level security;
alter table public.agricultural_inputs enable row level security;
alter table public.livestock_data enable row level security;

drop policy if exists "Authenticated users can view countries"
    on public.countries;

create policy "Authenticated users can view countries"
on public.countries
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can view datasets"
    on public.datasets;

create policy "Authenticated users can view datasets"
on public.datasets
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can view agricultural inputs"
    on public.agricultural_inputs;

create policy "Authenticated users can view agricultural inputs"
on public.agricultural_inputs
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can view livestock data"
    on public.livestock_data;

create policy "Authenticated users can view livestock data"
on public.livestock_data
for select
to authenticated
using (true);
